### ISSUE TITLE
Random units if not explitly set.

### ISSUE THREAD

**Issue by luksen99** [sbyrnes321/numericalunits#10]
Thank you very much for providing this package. Everything workes fine and it is super easy to use. What I realized recently though is that if you do not set `u.reset_units('SI')` explicitly it seems that the set of units are chosen randomly. At least I always got different results for the same calculation. 
Maybe a default unit would be practical.

**Comment by sbyrnes321** [comment]
If your calculation is free of mistakes, you will *not* get different results for the same calculation. I suggest that you keep randomization turned on: if you turn it off by using SI mode, you'll no longer be able to automatically catch dimensional-analysis errors. See the README at the bottom of https://github.com/sbyrnes321/numericalunits .
