### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by luksen99** [sbyrnes321/numericalunits#11]
Could you provide some documentation, that is which hotkeys match with which unit? (Maybe in the Wiki)
E.g.: If you want 1 nanometer you set `1*u.nm` but for other units Ångstrom or so it is less obvious.

**Comment by sbyrnes321** [comment]
Just read the source code - https://github.com/sbyrnes321/numericalunits/blob/master/numericalunits.py . I don't think it's necessary to have a separate file with a list. Most of the source code is exactly the list you're looking for, and I put comments next to any unit which is not self-evident. (But let me know if I missed something.)
