### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CDmaterial** [sbyrnes321/numericalunits#12]
Need help!
mac version: 10.15.1.
Typed: `pip install numericalunits` 
Got error:
ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fm/9zsn7zqs7dl9b24yx2ygn0140000gn/T/pip-install-rJ80y0/numericalunits/setup.py'"'"'; __file__='"'"'/private/var/folders/fm/9zsn7zqs7dl9b24yx2ygn0140000gn/T/pip-install-rJ80y0/numericalunits/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fm/9zsn7zqs7dl9b24yx2ygn0140000gn/T/pip-install-rJ80y0/numericalunits/pip-egg-info
         cwd: /private/var/folders/fm/9zsn7zqs7dl9b24yx2ygn0140000gn/T/pip-install-rJ80y0/numericalunits/
    Complete output (8 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fm/9zsn7zqs7dl9b24yx2ygn0140000gn/T/pip-install-rJ80y0/numericalunits/setup.py", line 5, in <module>
        from numericalunits import __version__
      File "numericalunits.py", line 26
        cm = mm = um = nm = pm = fm = km = angstrom = Å = lightyear = \
                                                      ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

**Comment by sbyrnes321** [comment]
It requires Python 3. You can use numericalunits 1.23 or earlier, or else install Python 3 (I recommend [Anaconda](https://www.anaconda.com/distribution/)).
