### ISSUE TITLE
Add Decibel and related units

### ISSUE THREAD

**Issue by mla-martin** [sbyrnes321/numericalunits#17]
I miss the units related to the dB ratio like dBm, dBW, dBV, dBA and so on. Does implementing that would work with the current concept?

**Comment by sbyrnes321** [comment]
It's not possible to implement that in the same scheme as everything else in this package. I think you could do it by defining it as a function—i.e., `dBV(13)` NOT `13 * dBV`. I don't want to put that in though, sorry.
