### ISSUE TITLE
Missing unit for radiation dose

### ISSUE THREAD

**Issue by hosseinjafar** [sbyrnes321/numericalunits#18]
Hi, thanks for the great package. 

I would like to add the unit for radiation dose deposited in material. 

The name of the unit is Gray, its symbol is Gy: 
1 Gy = 1 J/Kg.

**Comment by sbyrnes321** [comment]
Reasons I'm rejecting:

(1) You’re the first one to ask after 11 years, it seems not too widely used.

(2) If we add Gy then someone is going to want to add Sv, but Gy and Sv are dimensionally identical but importantly (life-or-death!) different and could plausibly get mixed up in practice, making it a terrible fit to this particular method of tracking units.

(3) If we add Gy then someone is going to want to add rad, but rad looks like radians which is confusing.

Anyway, you can straightforwardly add it in your own code. (Or fork this repository, if you prefer.)
