### ISSUE TITLE
add horsepower

### ISSUE THREAD

**Issue by iotium** [sbyrnes321/numericalunits#6]
It would be great if you had horsepower as unit of power
745.69987158227022 W to 1 hp
This is what wikipedia calls mechanical horsepower.

**Comment by sbyrnes321** [comment]
Thanks for the suggestion!

My reading suggests that imperial and metric horsepower are about equally widespread. (But the other versions mentioned on wikipedia are very obscure. Therefore I propose to add:
```
horsepower_imperial =  745.69...*W
horsepower_metric =  735.4...*W
```
(If you want shorter variable names you can do `from numericalunits import horsepower_imperial as hp` or whatever.)

Comments?

**Comment by iotium** [comment]
Sounds great!

**Comment by sbyrnes321** [comment]
see be47057 - it will appear in the next version
