### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by jayvdb** [sbyrnes321/numericalunits#9]
Hiya, this package is part of the openSUSE collection at https://build.opensuse.org/package/show/devel:languages:python:numeric/python-numericalunits

However currently it can only use the wheel uploaded to PyPI, which is not according to the packaging guidelines at https://en.opensuse.org/openSUSE:Packaging_Python

Would you be able to upload a 'sdist' to PyPI?

Also useful is creating GitHub tags for each release at https://github.com/sbyrnes321/numericalunits/releases , so those tarballs can also be used by packaging systems.

Finally, while I am here, has any thought been given to creating a basic smoke test suite?  These are useful for vendors even if they are very basic, as they allow checking compatibility with new python runtimes as they become available.

**Comment by sbyrnes321** [comment]
Oh neat, thanks for letting me know.

So far I've been running:

    python setup.py bdist_wheel
    twine upload dist/*

Next time I'll use:

    python setup.py bdist_wheel sdist
    twine upload dist/*

Does that sound right? Agree or disagree? I do python packaging sufficiently infrequently that I have to re-learn how it works each time.

Sure, I can start tagging versions.

When you say "smoke test suite", do you have something specific in mind, e.g. compatible with a particular automated testing framework? Otherwise I can just make a file `test.py` and you run it and it prints "All tests pass, hooray!" or whatever...

**Comment by jayvdb** [comment]
For the sdist to be useful, a `MANIFEST.in` is needed.  https://pypi.org/project/check-manifest/ can generate one for the repository.

For a basic smoke test, it would be better to be written in the stdlib [unittest](https://docs.python.org/2/library/unittest.html), then any runner can be used.  The tests could be as simple as (1) importing and checking a few of the attributes against pre-computed values, and then (2) a second test to invoke `set_derived_units_and_constants()` and check a few of those runtime globals against pre-computed values.  One part that might get complicated is the values might not be the same on all supported versions of Python; I've had trouble in the past with floats where different Python versions gave very slight differences, making the test logic a bit more complicated.  I've seen a few unittest addons which provide a 'almost equal' to handle this.

Which versions of Python do you intend to support with this package, as setup.py just says v2 and v3, while most software packages now only support v2.7 and v3.4+.

**Comment by sbyrnes321** [comment]
I think I did all your suggestions, but I'll leave this issue open until the next time I upload a new version to pypi, which will (hopefully) have the sdist. Let me know if you see anything else amiss, and thanks for your time.

**Comment by jayvdb** [comment]
Thank you, and https://build.opensuse.org/request/show/704097 submitted to use the new tarball from GitHub

**Comment by sbyrnes321** [comment]
I just uploaded & tagged version 1.23 with the sdist. All set?

**Comment by jayvdb** [comment]
Ideally add `recursive-include tests *.py` to MANIFEST.in so that the tests are in the sdist of the next release.

Also v1.23 switched from using Unix to DOS end-of-line markers.  I guess that wasnt intentional, and it causes the openSUSE web diff to not work as you can see at https://build.opensuse.org/request/show/705189

Thanks for your help with this.
